### ISSUE TITLE
Python > 3.4 does not convert float to hex via %x formatter

### ISSUE THREAD

**Issue by cstrotm** [bundy-dns/bundy#120]
# /usr/local/sbin/bundy -v
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/libexec/bundy/bundy-msgq", line 678, in run
    self.run_select()
  File "/usr/local/libexec/bundy/bundy-msgq", line 708, in run_select
    self.process_accept()
  File "/usr/local/libexec/bundy/bundy-msgq", line 332, in process_accept
    self.register_socket(newsocket)
  File "/usr/local/libexec/bundy/bundy-msgq", line 340, in register_socket
    lname = self.newlname()
  File "/usr/local/libexec/bundy/bundy-msgq", line 577, in newlname
    self.hostname)
TypeError: %x format: an integer is required, not float

**Comment by cstrotm** [comment]
proposed fix

```
    def newlname(self):
        """Generate a unique connection identifier for this socket.
        This is done by using an increasing counter and the current
        time."""
        self.connection_counter += 1
        return "%s_%s@%s" % (time.ctime(), float.hex(self.connection_counter),
                             self.hostname)
```
